version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Test
          command: |
            make test

      - run:
          name: Build
          command: |
            make build

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
            - ~/.cache/go-build

workflows:
  build-workflow:
    jobs:
      - build